### ISSUE TITLE
Regression with driver-conflict resolution

### ISSUE THREAD

**Issue by jcurtiss8086** [MikePopoloski/slang#1454]
Apologies for the complicated reproducer.  I wasn't able to create a small example from scratch and ended up taking the original module and slowly commenting out code while still keeping the two errors that are triggering.  In the remaining code, if any individual if-statement or for-loop is commented out at least one of the errors goes away.

The example passes in 8.0 and fails in 9.0, so I expect the issue is related to the analysis-layer changes.  I have not yet had time to run through a git-bisect to narrow it down to a specific commit.

```
driver_regress.sv:32:17: error: variable 't1[<unset>]' driven by always_comb procedure cannot be written to by any other process
                t1[p][c].b = '0;
                ^~~~~
driver_regress.sv:23:17: note: also assigned here
                t1[p][c].a = '0;
                ^~~~~~~~~~
driver_regress.sv:46:21: error: variable 't1[<unset>]' driven by always_comb procedure cannot be written to by any other process
                    t1[p][c].b = '1;
                    ^~~~~
driver_regress.sv:23:17: note: also assigned here
                t1[p][c].a = '0;
                ^~~~~~~~~~
```
```Systemverilog
module top #(
    parameter int unsigned P  = 4
);

    localparam C = 1;

    typedef struct packed {
        logic a;
        logic b;
    } type1;

    type1 [P-1:0][C-1:0] t1;

    typedef struct packed {
        logic a;
    } type2;

    type2 [P-1:0][C-1:0] t2_a, t2_b;

    always_comb begin
        for (int unsigned p=0; p<P; p++) begin
            for (int unsigned c=0; c<C; c++) begin
                t1[p][c].a = '0;
            end
        end
    end

    always_comb begin

        for (int unsigned p=0; p<P; p++) begin
            for (int unsigned c=0; c<C; c++ ) begin
                t1[p][c].b = '0;
            end

            for (int unsigned c=0; c<C; c++ ) begin
                t2_a[p][c].a = 1'b0;
            end

            for (int unsigned c=0; c<C; c++) begin
                if (~t2_b[p][c].a) begin
                end
            end

            for (int unsigned c=0; c<C; c++) begin
                for (int unsigned c=0; c<C; c++) begin
                    t1[p][c].b = '1;
                end
            end
        end
    end
```

**Comment by jcurtiss8086** [comment]
git-bisect confirmed that the example begins failing with 0f8667a92095e53ca70bdc9c035c4ee6d9b93371

The failure signature is slightly different at that commit
```
driver_regress.sv:32:17: error: variable 't1' driven by always_comb procedure cannot be written to by any other process
                t1[p][c].b = '0;
                ^~~~~~~~~~
driver_regress.sv:23:17: note: also assigned here
                t1[p][c].a = '0;
                ^~~~~~~~~~
```

**Comment by MikePopoloski** [comment]
Fixed in ecb769e154ab5991b70e6f00942119fbf4aebbcf
